#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql-volume
#  namespace: ns-test
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 2Gi
#  hostPath:
#    path: /tmp/vol-mysql/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume-claim
  namespace: ns-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
