apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-deployment
  namespace: ns-test
  labels:
    app: phpfpm
spec:
  selector:
    matchLabels:
      app: phpfpm
  replicas: 2
  template:
    metadata:
      labels:
        app: phpfpm
    spec:
      containers:
        - name: phpfpm
          image: php-test:1.0
          env:
            - name: DB_HOST
              value: mysql-service
            - name: DB_PW
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: rootpw
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-service
  namespace: ns-test
spec:
  type: ClusterIP
  ports:
    - port: 9000
  selector:
    app: phpfpm
